version: 2.1
commands:
  client_build:
    description: "Build Elements"
    steps:
      - run: npm install
      - run: npx isom transpile
      - run: npx isom test

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/elements

    steps:
      - checkout
      - client_build
