export const Colors = ({
  isPrimary,
  isSuccess,
  isInfo,
  isWarning,
  isDanger,
  isLink,
  isLight,
  isWhite,
  isDark,
  isBlack,
  isText,
}) => ({
  'is-primary': isPrimary,
  'is-success': isSuccess,
  'is-info': isInfo,
  'is-warning': isWarning,
  'is-danger': isDanger,
  'is-link': isLink,
  'is-light': isLight,
  'is-white': isWhite,
  'is-dark': isDark,
  'is-black': isBlack,
  'is-text': isText,
})

export const Sizes = ({
  isSmall,
  isNormal,
  isMedium,
  isLarge,
  isFullWidth,
}) => ({
  'is-small': isSmall,
  'is-normal': isNormal,
  'is-medium': isMedium,
  'is-large': isLarge,
  'is-fullwidth': isFullWidth,
})

export const Screens = ({
  isMobile,
  isFluid,
  isWideScreen,
  isFullHD,
  isFullHeight,
  isFullHeightWithNavBar,
}) => ({
  'is-mobile': isMobile,
  'is-fluid': isFluid,
  'is-widescreen': isWideScreen,
  'is-fullhd': isFullHD,
  'is-fullheight': isFullHeight,
  'is-fullheight-with-navbar': isFullHeightWithNavBar,
})

export const StyleOrState = ({
  isOutlined,
  isInverted,
  isLoading,
  isActive,
  isFocused,
  isHovered,
  isRounded,
  isStatic,
  isSelected,
}) => ({
  'is-loading': isLoading,
  'is-outlined': isOutlined,
  'is-active': isActive,
  'is-focused': isFocused,
  'is-inverted': isInverted,
  'is-hovered': isHovered,
  'is-rounded': isRounded,
  'is-static': isStatic,
  'is-selected': isSelected,
})

export const HasText = ({
  hasTextWhite,
  hasTextBlack,
  hasTextLight,
  hasTextDark,
  hasTextPrimary,
  hasTextInfo,
  hasTextLink,
  hasTextSuccess,
  hasTextWarning,
  hasTextDanger,
  hasTextBlackBis,
  hasTextBlackTer,
  hasTextGreyDarker,
  hasTextGreyDark,
  hasTextGrey,
  hasTextGreyLight,
  hasTextGreyLighter,
  hasTextWhiteTer,
  hasTextWhiteBis,
}) => ({
  'has-text-white': hasTextWhite,
  'has-text-black': hasTextBlack,
  'has-text-light': hasTextLight,
  'has-text-dark': hasTextDark,
  'has-text-primary': hasTextPrimary,
  'has-text-info': hasTextInfo,
  'has-text-link': hasTextLink,
  'has-text-success': hasTextSuccess,
  'has-text-warning	': hasTextWarning,
  'has-text-danger': hasTextDanger,
  'has-text-black-bis': hasTextBlackBis,
  'has-text-black-ter': hasTextBlackTer,
  'has-text-grey-darker': hasTextGreyDarker,
  'has-text-grey-dark': hasTextGreyDark,
  'has-text-grey': hasTextGrey,
  'has-text-grey-light': hasTextGreyLight,
  'has-text-grey-lighter': hasTextGreyLighter,
  'has-text-white-ter': hasTextWhiteTer,
  'has-text-white-bis': hasTextWhiteBis,
})
